services:
  - type: web
    name: atalas-school
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: composer install
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
